# Generated by Django 4.2.2 on 2024-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecommapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', models.TextField()),
                ('encrypted_text', models.TextField()),
                ('key', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
