# Generated by Django 4.2.2 on 2024-01-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecommapp', '0002_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
