# Generated by Django 4.2.2 on 2024-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecommapp', '0003_text_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='files/original/')),
                ('encrypted_file', models.FileField(upload_to='files/encrypted/')),
                ('key', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
