# Generated by Django 4.2.2 on 2024-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecommapp', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.ImageField(blank=True, null=True, upload_to='Original_Image')),
                ('encrypted_file', models.ImageField(blank=True, null=True, upload_to='Steganographed_Image')),
                ('key', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
