# Generated by Django 4.2.2 on 2024-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securecommapp', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
